### ISSUE TITLE
Importing Remi GPG key fails with "certificate verify failed"

### ISSUE THREAD

**Issue by varunvats** [geerlingguy/ansible-for-devops#425] opened 2021-10-15 19:41 UTC
Using the Vagrantfile as defined here: https://github.com/geerlingguy/ansible-for-devops/blob/master/nodejs/Vagrantfile. I first encountered this error when bringing up the VM. It is reproduced below with `vagrant provision`:

```
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Install EPEL repo.] ******************************************************
ok: [default]

TASK [Import Remi GPG key.] ****************************************************
fatal: [default]: FAILED! => {"changed": false, "msg": "failed to fetch key at https://rpms.remirepo.net/RPM-GPG-KEY-remi , error was: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by kenhia** [comment] 2021-10-16 05:04
Same here. I can see the public key on rpms.remirepo.net in browser (no cert warnings), and both curl and wget grab it find.

**Comment by CaptainTyphoo** [comment] 2021-10-30 13:35
The reason for the "certificate verify failed" error is that OpenSSL version 1.0.2 chooses a wrong (expired) root certificate (more details on this topic can be found [here](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/)). An easy workaround is to update the package`ca-certificates` before importing the Remi GPG Key:
```
- name: Update ca-certificates
  yum: name=ca-certificates state=latest
```
The real fix would probably need to be done by @geerlingguy by updating the CentOS7 vagrant box.

The issue about the not found `forever` command could be caused by your switch to CentOS 8, as the playbook installs `forever` to `/bin/forever` on CentOS 7.

**Comment by geerlingguy** [comment] 2021-10-31 04:48
Marking as a bug, this example definitely needs some updating.

**Closed** 2022-04-15 03:32 UTC
Labels: bug
