### ISSUE TITLE
ansible dynamic inventory doesn't work

### ISSUE THREAD

**Issue by mikamakusa** [geerlingguy/ansible-for-devops#126] opened 2019-02-11 23:48 UTC
Hi,

I'm trying to use your digitalocean.py script with ansible as a dynamic inventory script...but it's not working.
I'm running into the same following error everytime : `ERROR! A malformed block was encountered while loading a block`

It's not related to my ansible roles since they have been previously tested (it's working with vagrant).

Please help

**Comment by allamiro** [comment] 2019-04-06 06:02
please post the full error along with the  screenshot if possible it seems like  it looks like your handlers block isn't formatted correctly.  The error should  detail what line is causing the problem. I hope this will help.

**Comment by geerlingguy** [comment] 2019-08-20 21:25
@mikamakusa - Yeah, my guess is maybe there's a line that is missing a space, or is otherwise incorrectly formatted (maybe a tab character instead of spaces?).

You would need to post the entire error message (instead of just `ERROR! A malformed block was encountered while loading a block`) and ideally, also the exact command you're running. I can't reproduce this issue, so unless you can reproduce it and give some more detail, I would rather close this issue.

**Closed by geerlingguy** 2019-08-20 21:25 UTC
