### ISSUE TITLE
Tiller namespace misleading in Kubernetes chapter regarding Helm

### ISSUE THREAD

**Issue by mandrews4** [geerlingguy/ansible-for-devops#266] opened 2020-05-11 19:50 UTC
Second last paragraph of page 401 of the pdf begins with:

"Tiller needs to be allowed to manage certain resources in the cluster, so the first
two tasks in this playbook define a tiller namespace which Tiller will operate
within,"

but the tiller service account is created in the kube-system namespace.

Please reword.

**Comment by geerlingguy** [comment] 2020-05-11 20:07
@mandrews4 - That section is probably due for a rewrite now that Helm 3 is here and Ansible even has a new helm module in the `community.kubernetes` collection which allows easier interaction with Helm. This is slightly related to #202, in that sense...

**Comment by geerlingguy** [comment] 2020-05-13 04:20
Actually, I also have an issue open for all the Helm changes for Helm 3 in #249, so I'm closing this as a duplicate of that issue.

**Closed by geerlingguy** 2020-05-13 04:20 UTC
