### ISSUE TITLE
Dependency conflict php roles

### ISSUE THREAD

**Issue by pieterjanvandenberg** [geerlingguy/ansible-for-devops#31] opened 2016-04-27 21:21 UTC
Learning Ansible, so not sure how to deal with this. While running the tasks that install and configure PHP, this error appears: 

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [192.168.2.3] (item=[u'php', u'php-cli', u'php-common', u'php-devel', u'php-fpm', u'php-gd', u'php-imap', u'php-ldap', u'php-mbstring', u'php-opcache', u'php-pdo', u'php-pear', u'php-pecl-apc', u'php-xml', u'php-xmlrpc']) => {"changed": true, "failed": true, "item": ["php", "php-cli", "php-common", "php-devel", "php-fpm", "php-gd", "php-imap", "php-ldap", "php-mbstring", "php-opcache", "php-pdo", "php-pear", "php-pecl-apc", "php-xml", "php-xmlrpc"], **"msg": "Error: php-pecl-zendopcache conflicts with php-pecl-apc-3.1.9-2.el6.x86_64\n", "rc": 1,**

I'm Running Ansible 2.0.2.0 and Vagrant 1.8.1

**Comment by geerlingguy** [comment] 2016-04-29 01:55
@pieterjanvandenberg - Which example are you running when that error occurs—also, which OS are you using? (CentOS 7, or Ubuntu 14.04... or something else?)

**Comment by pieterjanvandenberg** [comment] 2016-04-29 05:01
Host OS is Ubuntu 14.04, same as the guest OSes. Running the lamp-infrastructure example. 
Op 29 apr. 2016 03:55 schreef Jeff Geerling <notifications@github.com>:@pieterjanvandenberg - Which example are you running when that error occurs—also, which OS are you using? (CentOS 7, or Ubuntu 14.04... or something else?)

**Comment by geerlingguy** [comment] 2016-07-22 02:01
I'm retesting the example now. The DigitalOcean portion will also need some updating due to the new v2 API in Ansible 1.9.5/2.0+

**Comment by geerlingguy** [comment] 2016-07-22 02:33
This may have been a temporary issue with some of the role versions that were out in April; I can't reproduce this issue now—and I'll likely be updating more of the example in the next major book revision, so closing this issue for now.

**Closed by geerlingguy** 2016-07-22 02:33 UTC
