### ISSUE TITLE
forever list fails : [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by pixeline** [geerlingguy/ansible-for-devops#85] opened 2018-02-04 01:28 UTC
Using Ansible 2.4.2.0; Darwin

When running the [nodejs provisioning playbook](https://github.com/geerlingguy/ansible-for-devops/blob/master/nodejs/provisioning/playbook.yml#L28-L47), it keeps failing when it reaches this task:

https://github.com/geerlingguy/ansible-for-devops/blob/ed1f0325bab17b9115b355403b9579e68634de66/nodejs/provisioning/playbook.yml#L40

The error message :

```shell
[Errno 2] No such file or directory
fatal: [domain.com]: FAILED! => {"changed": false, "cmd": "forever list", "rc": 2}
```

The full task:

```yml
- name: "Check list of running Node.js apps."
  command: forever list
  register: forever_list
  changed_when: false
``` 

I've triple-checked that the app.js file is there. Why does it not find it ?

**Comment by pavarotti305** [comment] 2018-02-04 12:49
Hi, Here my code source is perfectly working,

---
# tasks file for nodejs
- name: Install Epel Release.
yum: name=epel-release state=present
- name: Upgrade all Packages.
yum: name=* state=latest
- name: Stopped Firewall for test environment.
service: name=firewalld state=stopped
- name: Install Node Package Manager.
yum: name=npm state=present enablerepo=epel
- name: Install Forever to run Nodejs.
npm: name=forever global=yes state=present
- name: Ensure Node.js app folder exist.
file: "path={{ node_apps_location }} state=directory"
- name: Copy example Node.js app to Server.
copy: "src=files dest={{ node_apps_location }}"
- name: Install app dependencies defined in package.json.
npm: path={{ node_apps_location }}/files
- name: Check list of running Node.js apps.
command: forever list
register: forever_list
changed_when: false
- name: Start example Node.js app.
command: "forever start {{ node_apps_location}}/files/app.js"
when: "forever_list.stdout.find('{{ node_apps_location }}/files/app.js') ==
-1"


Best regards,

Lucien NTUMBA,
Network Systems Engineer and Software Developer.



2018-02-04 1:28 GMT+00:00 Alexandre Plennevaux <notifications@github.com>:

**Comment by pavarotti305** [comment] 2018-02-04 12:56
And verify the path if is set on the right side this error looks like your
directory is not set and when ansible try to find it is not where you
define the path try to look on my source repository he can help
https://github.com/pavarotti305/aws_elastic_beanstalk


Best regards,

Lucien NTUMBA,
Network Systems Engineer and Software Developer.



2018-02-04 1:28 GMT+00:00 Alexandre Plennevaux <notifications@github.com>:

**Comment by pixeline** [comment] 2018-02-05 08:30
The path is correct AFAICS. 

Here is a verbose log:

````shell
[Errno 2] No such file or directory
The full traceback is:
  File "/tmp/ansible_6kgVoL/ansible_modlib.zip/ansible/module_utils/basic.py", line 2762, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception

fatal: [inside.becode.org]: FAILED! => {
    "changed": false,
    "cmd": "forever list",
    "invocation": {
        "module_args": {
            "_raw_params": "forever list",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 2
}
```

**Comment by shakedlokits** [comment] 2018-08-05 18:43
Any solution on this one?

**Comment by geerlingguy** [comment] 2018-08-09 02:27
I just tested the playbook and didn't have an issue—using Ansible 2.6.2, macOS 10.13, Vagrant 2.1.2.

Additionally, the CI tests have been passing for months, for example:

nodejs playbook: https://travis-ci.org/geerlingguy/ansible-for-devops/jobs/413411449
nodejs-role playbook: https://travis-ci.org/geerlingguy/ansible-for-devops/jobs/413411450

Can you provide an exact set of steps to reproduce? For example, I did the following:

  1. Clone this repository.
  2. Change into the `nodejs` directory.
  3. Run `vagrant up`.

After vagrant completes its provisioning, there are no errors and the app is running as it should be.

**Comment by geerlingguy** [comment] 2018-08-09 02:30
It looks like you may be using a modified version of this playbook (note the `/srv/www/inside.domain.org/current/web/attendances` directory being used...). I'm wondering if `forever` is not installed at all on the server, or it is installed under a different user, or it is installed but is not in a directory accessible in the system `$PATH`? If you log into the server and run the command `forever` does it fail as well?

In any case, I'm closing this for now as I can't reproduce the issue with the example from the book; if you're using a custom playbook, it might be best to ask about bugs or problems in the Ansible Project Google Group, or on Stack Exchange or something like that.

This repository is meant for help with the actual examples in the book, or with bugs in the examples from the book.

**Closed by geerlingguy** 2018-08-09 02:30 UTC

**Comment by JamesCHub** [comment] 2020-11-03 19:54
> Using Ansible 2.4.2.0; Darwin
> 
> When running the [nodejs provisioning playbook](https://github.com/geerlingguy/ansible-for-devops/blob/master/nodejs/provisioning/playbook.yml#L28-L47), it keeps failing when it reaches this task:
> 
> https://github.com/geerlingguy/ansible-for-devops/blob/ed1f0325bab17b9115b355403b9579e68634de66/nodejs/provisioning/playbook.yml#L40
> 
> The error message :
> 
> ```shell
> [Errno 2] No such file or directory
> fatal: [domain.com]: FAILED! => {"changed": false, "cmd": "forever list", "rc": 2}
> ```
> 
> The full task:
> 
> ```yaml
> - name: "Check list of running Node.js apps."
>   command: forever list
>   register: forever_list
>   changed_when: false
> ```
> 
> I've triple-checked that the app.js file is there. Why does it not find it ?

I had the same issue - in my case the cause was using the Vagrant VMs from the previous chapter.   Once I provisioned the VM defined here https://github.com/geerlingguy/ansible-for-devops/blob/master/nodejs/Vagrantfile everything worked.

Note that the book alludes to this in an info note just prior to this section which I missed the first time around.

**Comment by digialien** [comment] 2022-12-11 19:03
You need to include the full path of the command forever in the plays, i.e /usr/local/bin/forever, instead of forever
